using MentorTaskFlow.Domain.Common;

namespace MentorTaskFlow.Domain.Analytics;

/// <summary>What the summary is about (TZ 10.16).</summary>
/// <remarks>
/// The shape of the row follows from the scope and is enforced in the database by
/// <c>ck_ai_summaries_scope_shape</c>: a personal or team report names a branch and a category, a
/// branch report names a branch only, and the organization aggregate names neither.
/// </remarks>
public enum AiSummaryScope
{
    Personal = 0,
    Team = 1,
    Branch = 2,
    Organization = 3,
}

public enum AiSummaryStatus
{
    Pending = 0,
    Completed = 1,
    Failed = 2,
}

/// <summary>
/// A generated report and the inputs that make it reproducible (TZ 10.16, 22.5).
/// </summary>
/// <remarks>
/// <para>
/// The row <b>is</b> the cache: <see cref="CacheKey"/> is unique, and it folds in the tenant scope,
/// the period, a hash of the metrics that were sent, the prompt version and the model. A repeat
/// request that resolves to the same key returns this content without reaching the provider
/// (<c>AI-010</c>); anything that would change the answer changes the key instead of quietly serving a
/// stale one.
/// </para>
/// <para>
/// <see cref="OrganizationId"/> and <see cref="BranchId"/> are part of that key and are immutable
/// (<c>TEN-076</c>, <c>TEN-018</c>). Without them the category <c>C#</c> of the head office and the
/// category <c>C#</c> of Khujand would produce the same key for the same period, and the second
/// request would be answered with the first branch's report — a leak that surfaces as a cache hit
/// rather than as an error.
/// </para>
/// </remarks>
public sealed class AiSummary : BaseEntity
{
    public const int CacheKeyMaxLength = 200;
    public const int MetricsHashLength = 64;
    public const int PromptVersionMaxLength = 16;
    public const int ModelIdMaxLength = 64;
    public const int FailureReasonMaxLength = 256;

    /// <summary>Always required; fixed at creation (<c>TEN-018</c>).</summary>
    public Guid OrganizationId { get; private set; }

    /// <summary>Null only for <see cref="AiSummaryScope.Organization"/>.</summary>
    public Guid? BranchId { get; private set; }

    /// <summary>Required for <see cref="AiSummaryScope.Personal"/> and <see cref="AiSummaryScope.Team"/>.</summary>
    public Guid? CategoryId { get; private set; }

    public AiSummaryScope Scope { get; private set; }

    /// <summary>Required for <see cref="AiSummaryScope.Personal"/>.</summary>
    public Guid? SubjectUserId { get; private set; }

    public DateOnly PeriodStart { get; private set; }

    public DateOnly PeriodEnd { get; private set; }

    public string CacheKey { get; private set; } = null!;

    /// <summary>SHA-256 of the canonical JSON of the metrics that were sent.</summary>
    public string MetricsHash { get; private set; } = null!;

    public string PromptVersion { get; private set; } = null!;

    public string ModelId { get; private set; } = null!;

    public AiSummaryStatus Status { get; private set; }

    /// <summary>Required once <see cref="Status"/> is <see cref="AiSummaryStatus.Completed"/>.</summary>
    public string? Content { get; private set; }

    public string? FailureReason { get; private set; }

    public int? InputTokens { get; private set; }

    public int? OutputTokens { get; private set; }

    public Guid RequestedById { get; private set; }

    /// <summary>
    /// When this subject was last regenerated by force (<c>AI-011</c>).
    /// </summary>
    /// <remarks>
    /// <b>Addition to the field list of 10.16, deliberate and flagged.</b> <c>AI-011</c> caps forced
    /// regeneration at once a day <b>per subject</b>, and a subject spans rows: one period per row,
    /// each with its own key. Nothing in the documented columns can express «this subject was forced
    /// today», so the limit could only be enforced per row — which is not the limit that was asked
    /// for, since a caller would clear it simply by shifting the period by a day.
    /// </remarks>
    public DateTimeOffset? LastForcedAt { get; private set; }

    private AiSummary()
    {
    }

    /// <summary>Opens a row for a generation that is about to be attempted.</summary>
    public static AiSummary Start(
        Guid organizationId,
        Guid? branchId,
        Guid? categoryId,
        AiSummaryScope scope,
        Guid? subjectUserId,
        DateOnly periodStart,
        DateOnly periodEnd,
        string cacheKey,
        string metricsHash,
        string promptVersion,
        string modelId,
        Guid requestedById,
        DateTimeOffset now)
    {
        if (organizationId == Guid.Empty)
        {
            throw new DomainException(
                DomainErrorCodes.ValidationFailed,
                "AiSummary.OrganizationId обязателен всегда (TEN-076).");
        }

        // The same shape the CHECK constraint enforces, stated here so a violation is a domain error
        // rather than a database error surfacing as a 500 (10.16).
        var shapeIsValid = scope switch
        {
            AiSummaryScope.Organization => branchId is null && categoryId is null,
            AiSummaryScope.Branch => branchId is not null && categoryId is null,
            _ => branchId is not null && categoryId is not null,
        };

        if (!shapeIsValid)
        {
            throw new DomainException(
                DomainErrorCodes.ValidationFailed,
                $"Состав scope '{scope}' не соответствует ck_ai_summaries_scope_shape.");
        }

        if (scope is AiSummaryScope.Personal && subjectUserId is null)
        {
            throw new DomainException(
                DomainErrorCodes.ValidationFailed,
                "AiSummary.SubjectUserId обязателен при Scope='Personal'.");
        }

        if (string.IsNullOrWhiteSpace(cacheKey) || cacheKey.Length > CacheKeyMaxLength)
        {
            throw new DomainException(DomainErrorCodes.ValidationFailed, "AiSummary.CacheKey обязателен.");
        }

        if (metricsHash?.Length != MetricsHashLength)
        {
            throw new DomainException(
                DomainErrorCodes.ValidationFailed,
                "AiSummary.MetricsHash — SHA-256 в шестнадцатеричном виде (64 символа).");
        }

        return new AiSummary
        {
            OrganizationId = organizationId,
            BranchId = branchId,
            CategoryId = categoryId,
            Scope = scope,
            SubjectUserId = subjectUserId,
            PeriodStart = periodStart,
            PeriodEnd = periodEnd,
            CacheKey = cacheKey,
            MetricsHash = metricsHash,
            PromptVersion = promptVersion,
            ModelId = modelId,
            Status = AiSummaryStatus.Pending,
            RequestedById = requestedById,
            CreatedAt = now,
        };
    }

    public void Complete(string content, int? inputTokens, int? outputTokens)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            throw new DomainException(
                DomainErrorCodes.ValidationFailed,
                "Content обязателен при Status='Completed' (10.16).");
        }

        Status = AiSummaryStatus.Completed;
        Content = content;
        FailureReason = null;
        InputTokens = inputTokens;
        OutputTokens = outputTokens;
    }

    /// <summary>
    /// Records a failed attempt.
    /// </summary>
    /// <remarks>
    /// The reason is an error code, never the provider's message: a provider response can echo the
    /// prompt back, and the prompt carries the organization's data (<c>AUD-022</c>).
    /// </remarks>
    public void Fail(string reason)
    {
        Status = AiSummaryStatus.Failed;
        FailureReason = reason.Length <= FailureReasonMaxLength ? reason : reason[..FailureReasonMaxLength];
        Content = null;
    }

    /// <summary>Marks the row as regenerated on the caller's demand (<c>AI-011</c>).</summary>
    public void MarkForced(DateTimeOffset now) => LastForcedAt = now;
}
