using MentorTaskFlow.Domain.Common;

namespace MentorTaskFlow.UnitTests.Common;

public sealed class BaseEntityTests
{
    private sealed class SampleEntity : AuditableEntity
    {
        public SampleEntity()
        {
        }

        public SampleEntity(Guid id) : base(id)
        {
        }
    }

    private sealed class OtherEntity : BaseEntity;

    /// <summary><c>DEPLOY-003</c>: primary keys are UUID v7, generated by the application.</summary>
    [Fact]
    public void Id_is_a_version_7_uuid()
    {
        new SampleEntity().Id.Version.ShouldBe(7);
    }

    /// <summary>
    /// Monotonicity is the whole reason for choosing v7 over v4: it gives B-tree insert locality.
    /// </summary>
    [Fact]
    public void Ids_increase_over_time()
    {
        var first = new SampleEntity().Id;
        Thread.Sleep(2);
        var second = new SampleEntity().Id;

        first.CompareTo(second).ShouldBeLessThan(0);
    }

    [Fact]
    public void Entities_of_the_same_type_with_the_same_id_are_equal()
    {
        var id = Guid.CreateVersion7();

        new SampleEntity(id).ShouldBe(new SampleEntity(id));
    }

    [Fact]
    public void Entities_of_different_types_are_never_equal()
    {
        var sample = new SampleEntity();

        sample.Equals(new OtherEntity()).ShouldBeFalse();
    }
}
