namespace MentorTaskFlow.Domain.Common;

/// <summary>
/// Base for every persisted entity.
/// </summary>
/// <remarks>
/// Primary keys are UUID v7 generated by the application (<c>DEPLOY-003</c>): monotonicity gives
/// B-tree insert locality and avoids the index fragmentation of UUID v4, without a round trip to
/// the database for the value. Database-side <c>gen_random_uuid()</c> is used only in seed scripts.
/// </remarks>
public abstract class BaseEntity
{
    public Guid Id { get; protected set; } = Guid.CreateVersion7();

    /// <summary>Always UTC — <c>timestamptz</c> in PostgreSQL (<c>DEPLOY-002</c>).</summary>
    public DateTimeOffset CreatedAt { get; protected set; }

    protected BaseEntity()
    {
    }

    protected BaseEntity(Guid id) => Id = id;

    public override bool Equals(object? obj) =>
        obj is BaseEntity other && GetType() == other.GetType() && Id == other.Id && Id != Guid.Empty;

    public override int GetHashCode() => HashCode.Combine(GetType(), Id);
}

/// <summary>Entity that tracks its last modification. Append-only entities do not derive from this.</summary>
public abstract class AuditableEntity : BaseEntity
{
    public DateTimeOffset UpdatedAt { get; protected set; }

    protected AuditableEntity()
    {
    }

    protected AuditableEntity(Guid id) : base(id)
    {
    }
}
