// <auto-generated />
using System;
using System.Text.Json;
using MentorTaskFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentorTaskFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MentorTaskFlowDbContext))]
    [Migration("20260814085927_Reviews")]
    partial class Reviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentorTaskFlow.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_id");

                    b.Property<Guid>("AssignedToId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_id");

                    b.Property<string>("AutoGenerationKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("auto_generation_key");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledById")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("current_due_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FirstSubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_submitted_at");

                    b.Property<DateOnly?>("GeneratedForDate")
                        .HasColumnType("date")
                        .HasColumnName("generated_for_date");

                    b.Property<DateTimeOffset>("InitialDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("initial_due_at");

                    b.Property<int>("LastEventSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_event_sequence");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("OverdueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("overdue_at");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("review_started_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TopicAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_assignment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .HasName("ak_assignments_id_organization_id_branch_id_category_id");

                    b.HasIndex("ApprovedAt")
                        .HasDatabaseName("ix_assignments_approved_at")
                        .HasFilter("approved_at IS NOT NULL");

                    b.HasIndex("Status", "CurrentDueAt")
                        .HasDatabaseName("ix_assignments_overdue_scan")
                        .HasFilter("status IN ('Assigned','NeedsRework')");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .HasDatabaseName("ix_assignments_category_id_organization_id_branch_id");

                    b.HasIndex("OrganizationId", "BranchId", "AutoGenerationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_assignments_auto_generation_key_scoped")
                        .HasFilter("source = 'Auto'");

                    b.HasIndex("Id", "OrganizationId", "BranchId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignments_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "Status")
                        .HasDatabaseName("ix_assignments_suggestion_queue")
                        .HasFilter("status = 'Suggested'");

                    b.HasIndex("TopicAssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasDatabaseName("ix_assignments_topic_assignment_id_organization_id_branch_id_c");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "AssignedToId", "Status", "CurrentDueAt")
                        .HasDatabaseName("ix_assignments_scope_assignee_status_due");

                    b.ToTable("assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignments_approved_fields", "(status <> 'Approved') OR (approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_assignments_auto_fields", "(source = 'Auto' AND generated_for_date IS NOT NULL AND auto_generation_key IS NOT NULL)\r\nOR (source = 'Manual' AND generated_for_date IS NULL AND auto_generation_key IS NULL)");

                            t.HasCheckConstraint("ck_assignments_cancel_fields", "(status <> 'Cancelled')\r\nOR (cancelled_at IS NOT NULL AND cancelled_by_id IS NOT NULL\r\n    AND char_length(cancel_reason) BETWEEN 5 AND 500)");

                            t.HasCheckConstraint("ck_assignments_due_order", "current_due_at >= initial_due_at");

                            t.HasCheckConstraint("ck_assignments_status_allowed", "status IN ('Draft','Suggested','Assigned','Submitted','InReview','NeedsRework','Overdue','Approved','Cancelled')");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Assignments.TaskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("MetadataSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("metadata_schema_version");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_status");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("pk_task_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_task_events_correlation_id");

                    b.HasIndex("AssignmentId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_task_events_assignment_sequence");

                    b.HasIndex("OrganizationId", "BranchId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_task_events_organization_branch_occurred_at");

                    b.HasIndex("AssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasDatabaseName("ix_task_events_assignment_id_organization_id_branch_id_categor");

                    b.ToTable("task_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_events_system_actor", "(event_type NOT IN ('MarkedOverdue','SuggestedCreated')) OR actor_id IS NULL");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorAdminScope")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_admin_scope");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("http_method");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("MetadataSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("metadata_schema_version");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Path")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("path");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_audit_logs_branch_id_organization_id");

                    b.HasIndex("OrganizationId", "ActorId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_logs_organization_actor_occurred_at");

                    b.HasIndex("OrganizationId", "BranchId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_logs_organization_branch_occurred_at");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_organization_entity");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_actor_shape", "(actor_type = 'System' AND actor_id IS NULL) OR (actor_type = 'User' AND actor_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_logs_branch_scope", "branch_id IS NOT NULL OR action IN ('audit.read','bootstrap.provision','branch.activate','branch.create','branch.deactivate','branch.make_head_office','branch.update','organization.update','report.organization_export','security.scope_override_rejected','storage.cross_scope_inconsistency','user.change_admin_scope','user.change_branch','user.create_organization_admin')");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId")
                        .HasName("ak_categories_id_organization_id_branch_id");

                    b.HasIndex("BranchId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_branch_normalized_name");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_categories_branch_id_organization_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "IsActive")
                        .HasDatabaseName("ix_categories_organization_branch_is_active");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.CategorySettings", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<bool>("AllowLateSubmission")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_late_submission");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("DeadlineReminderHours")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_reminder_hours");

                    b.Property<int>("DefaultAssignmentDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_assignment_due_days");

                    b.Property<TimeOnly>("DefaultDueTimeLocal")
                        .HasColumnType("time")
                        .HasColumnName("default_due_time_local");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId")
                        .HasName("pk_category_settings");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_settings_category_id_organization_id_branch_id");

                    b.ToTable("category_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_settings_due_days", "default_assignment_due_days BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_category_settings_reminder_hours", "deadline_reminder_hours BETWEEN 1 AND 168");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason_revoked");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_user_family");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Identity.UserSecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_security_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_user_security_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ux_user_security_tokens_active")
                        .HasFilter("used_at IS NULL AND invalidated_at IS NULL");

                    b.ToTable("user_security_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_security_tokens_purpose_allowed", "purpose IN ('SetPassword','ResetPassword')");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Notifications.NotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsSystemAlert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_alert");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("payload_schema_version");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_outbox_dedup");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_outbox_user_id");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_notification_outbox_branch_id_organization_id");

                    b.HasIndex("Status", "LockedAt")
                        .HasDatabaseName("ix_notification_outbox_processing")
                        .HasFilter("status = 'Processing'");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_outbox_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("OrganizationId", "BranchId", "Status", "CreatedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_notification_outbox_organization_branch_status_created_at");

                    b.ToTable("notification_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_outbox_attempts", "attempts BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_notification_outbox_branch_scope", "branch_id IS NOT NULL OR event_type IN ('BranchWithoutAdmin','NotificationDeadLetter','OrganizationSystemAlert','UserInvitation')");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<DateTimeOffset?>("ReworkDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("rework_due_at");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_reviews_assignment_id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_submission");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "CreatedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_reviews_scope_created_at");

                    b.HasIndex("SubmissionId", "OrganizationId", "BranchId", "CategoryId")
                        .HasDatabaseName("ix_reviews_submission_scope");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_decision_allowed", "decision IN ('Approved','NeedsRework')");

                            t.HasCheckConstraint("ck_reviews_decision_fields", "(decision = 'NeedsRework' AND char_length(comment) BETWEEN 10 AND 3000 AND rework_due_at IS NOT NULL) OR (decision = 'Approved' AND rework_due_at IS NULL)");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Schedule.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .HasName("ak_topics_id_organization_id_branch_id_category_id");

                    b.HasIndex("CategoryId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_topics_category_day");

                    b.HasIndex("CategoryId", "PlannedDate")
                        .IsUnique()
                        .HasDatabaseName("ux_topics_category_planned_date")
                        .HasFilter("planned_date IS NOT NULL AND is_active = true");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .HasDatabaseName("ix_topics_category_id_organization_id_branch_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_topics_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "IsActive", "PlannedDate")
                        .HasDatabaseName("ix_topics_organization_branch_category_active_planned_date");

                    b.ToTable("topics", null, t =>
                        {
                            t.HasCheckConstraint("ck_topics_day_number", "day_number > 0");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Schedule.TopicAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topic_assignments");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .HasName("ak_topic_assignments_id_organization_id_branch_id_category_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_topic_assignments_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "IsActive")
                        .HasDatabaseName("ix_topic_assignments_organization_branch_category_active");

                    b.HasIndex("TopicId", "OrganizationId", "BranchId", "CategoryId")
                        .HasDatabaseName("ix_topic_assignments_topic_id_organization_id_branch_id_catego");

                    b.ToTable("topic_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_topic_assignments_type_allowed", "type IN ('Presentation','ClassTask','HomeTask')");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("ConversionStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("conversion_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("file_extension");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_late");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("PreviewStorageKey")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("preview_storage_key");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256_hash");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .HasName("ak_submissions_id_organization_id_branch_id_category_id");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_submissions_sha256_hash");

                    b.HasIndex("AssignmentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_submissions_assignment_version");

                    b.HasIndex("AssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasDatabaseName("ix_submissions_assignment_scope");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "SubmittedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_submissions_scope_submitted_at");

                    b.ToTable("submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_conversion_status", "conversion_status IS NULL");

                            t.HasCheckConstraint("ck_submissions_extension_allowed", "file_extension IN ('Pdf','Pptx')");

                            t.HasCheckConstraint("ck_submissions_preview_key", "(file_extension = 'Pdf' AND preview_storage_key = storage_key) OR (file_extension = 'Pptx' AND preview_storage_key IS NULL)");

                            t.HasCheckConstraint("ck_submissions_sha256_format", "sha256_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_submissions_size_bounds", "file_size_bytes > 0 AND file_size_bytes <= 52428800");

                            t.HasCheckConstraint("ck_submissions_version_positive", "version_number >= 1");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_head_office");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_branches_id_organization_id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_single_head_office")
                        .HasFilter("is_head_office = true");

                    b.HasIndex("Id", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_id_organization");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_branches_organization_is_active");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_normalized_name");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_code_format", "code ~ '^[A-Z0-9][A-Z0-9-]*$' AND char_length(code) BETWEEN 2 AND 32");

                            t.HasCheckConstraint("ck_branches_name_length", "char_length(name) BETWEEN 2 AND 200");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_normalized_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) BETWEEN 2 AND 80");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminScope")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("admin_scope");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_until");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("telegram_chat_id");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_active_lead_per_category")
                        .HasFilter("role = 'Lead' AND is_active = true");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_telegram_chat_id")
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_users_branch_id_organization_id");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .HasDatabaseName("ix_users_category_id_organization_id_branch_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "Role", "IsActive")
                        .HasDatabaseName("ix_users_organization_branch_role_is_active");

                    b.HasIndex("OrganizationId", "Role", "AdminScope", "IsActive")
                        .HasDatabaseName("ix_users_organization_role_admin_scope_is_active");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "Role", "IsActive")
                        .HasDatabaseName("ix_users_organization_branch_category_role_is_active");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_admin_scope_allowed", "admin_scope IS NULL OR admin_scope IN ('Organization','Branch')");

                            t.HasCheckConstraint("ck_users_role_admin_scope", "(role = 'Admin' AND admin_scope IS NOT NULL) OR (role <> 'Admin' AND admin_scope IS NULL)");

                            t.HasCheckConstraint("ck_users_role_allowed", "role IN ('Admin','Lead','Mentor')");

                            t.HasCheckConstraint("ck_users_role_category", "(role = 'Admin' AND category_id IS NULL) OR (role IN ('Lead','Mentor') AND category_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_scope_shape", "(role = 'Admin' AND admin_scope = 'Organization' AND branch_id IS NULL AND category_id IS NULL)\r\nOR (role = 'Admin' AND admin_scope = 'Branch' AND branch_id IS NOT NULL AND category_id IS NULL)\r\nOR (role IN ('Lead','Mentor') AND branch_id IS NOT NULL AND category_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserBranchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NewBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_branch_id");

                    b.Property<Guid?>("NewCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_category_id");

                    b.Property<Guid?>("OldBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_branch_id");

                    b.Property<Guid?>("OldCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_category_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_branch_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_branch_history_user_id");

                    b.HasIndex("NewBranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_branch_history_new_branch_id_organization_id");

                    b.HasIndex("OldBranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_branch_history_old_branch_id_organization_id");

                    b.HasIndex("OrganizationId", "UserId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_branch_history_organization_user_changed_at");

                    b.ToTable("user_branch_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_branch_history_change", "old_branch_id IS DISTINCT FROM new_branch_id");

                            t.HasCheckConstraint("ck_user_branch_history_reason", "char_length(reason) BETWEEN 5 AND 500");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserCategoryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NewCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_category_id");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("new_role");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("PreviousCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_category_id");

                    b.Property<string>("PreviousRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_role");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_category_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_category_history_user_id");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_category_history_branch_id_organization_id");

                    b.HasIndex("OrganizationId", "UserId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_category_history_organization_user_changed_at");

                    b.ToTable("user_category_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_category_history_reason", "char_length(reason) BETWEEN 5 AND 500");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_category_scope");

                    b.HasOne("MentorTaskFlow.Domain.Schedule.TopicAssignment", null)
                        .WithMany()
                        .HasForeignKey("TopicAssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assignments_template_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Assignments.TaskEvent", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_events_assignment_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_organization");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.Category", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.CategorySettings", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithOne()
                        .HasForeignKey("MentorTaskFlow.Domain.Categories.CategorySettings", "CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("MentorTaskFlow.Domain.Categories.Category", "Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_settings_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Identity.UserSecurityToken", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_security_tokens_user");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Notifications.NotificationOutbox", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_outbox_organization");

                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_outbox_user");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_outbox_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Reviews.Review", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId", "OrganizationId", "BranchId", "CategoryId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_submission_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Schedule.Topic", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topics_category_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Schedule.TopicAssignment", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Schedule.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId", "OrganizationId", "BranchId", "CategoryId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topic_assignments_topic_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Submissions.Submission", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId", "OrganizationId", "BranchId", "CategoryId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_assignment_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Branch", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_organization");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.User", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organization");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_branch_scope");

                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_category_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserBranchHistory", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_history_user");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("NewBranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_branch_history_new_branch_scope");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("OldBranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_branch_history_old_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserCategoryHistory", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_history_user");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_history_scope");
                });
#pragma warning restore 612, 618
        }
    }
}
