// <auto-generated />
using System;
using MentorTaskFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentorTaskFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MentorTaskFlowDbContext))]
    partial class MentorTaskFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("Id", "OrganizationId", "BranchId")
                        .HasName("ak_categories_id_organization_id_branch_id");

                    b.HasIndex("BranchId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_branch_normalized_name");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_categories_branch_id_organization_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "IsActive")
                        .HasDatabaseName("ix_categories_organization_branch_is_active");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.CategorySettings", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<bool>("AllowLateSubmission")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_late_submission");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("DeadlineReminderHours")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_reminder_hours");

                    b.Property<int>("DefaultAssignmentDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_assignment_due_days");

                    b.Property<TimeOnly>("DefaultDueTimeLocal")
                        .HasColumnType("time")
                        .HasColumnName("default_due_time_local");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId")
                        .HasName("pk_category_settings");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_settings_category_id_organization_id_branch_id");

                    b.ToTable("category_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_settings_due_days", "default_assignment_due_days BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_category_settings_reminder_hours", "deadline_reminder_hours BETWEEN 1 AND 168");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_head_office");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_branches_id_organization_id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_single_head_office")
                        .HasFilter("is_head_office = true");

                    b.HasIndex("Id", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_id_organization");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_branches_organization_is_active");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_normalized_name");

                    b.ToTable("branches", null, t =>
                        {
                            t.HasCheckConstraint("ck_branches_code_format", "code ~ '^[A-Z0-9][A-Z0-9-]*$' AND char_length(code) BETWEEN 2 AND 32");

                            t.HasCheckConstraint("ck_branches_name_length", "char_length(name) BETWEEN 2 AND 200");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_normalized_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) BETWEEN 2 AND 80");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminScope")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("admin_scope");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_until");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("telegram_chat_id");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_active_lead_per_category")
                        .HasFilter("role = 'Lead' AND is_active = true");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_telegram_chat_id")
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_users_branch_id_organization_id");

                    b.HasIndex("CategoryId", "OrganizationId", "BranchId")
                        .HasDatabaseName("ix_users_category_id_organization_id_branch_id");

                    b.HasIndex("Id", "OrganizationId", "BranchId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_id_scope");

                    b.HasIndex("OrganizationId", "BranchId", "Role", "IsActive")
                        .HasDatabaseName("ix_users_organization_branch_role_is_active");

                    b.HasIndex("OrganizationId", "Role", "AdminScope", "IsActive")
                        .HasDatabaseName("ix_users_organization_role_admin_scope_is_active");

                    b.HasIndex("OrganizationId", "BranchId", "CategoryId", "Role", "IsActive")
                        .HasDatabaseName("ix_users_organization_branch_category_role_is_active");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_admin_scope_allowed", "admin_scope IS NULL OR admin_scope IN ('Organization','Branch')");

                            t.HasCheckConstraint("ck_users_role_admin_scope", "(role = 'Admin' AND admin_scope IS NOT NULL) OR (role <> 'Admin' AND admin_scope IS NULL)");

                            t.HasCheckConstraint("ck_users_role_allowed", "role IN ('Admin','Lead','Mentor')");

                            t.HasCheckConstraint("ck_users_role_category", "(role = 'Admin' AND category_id IS NULL) OR (role IN ('Lead','Mentor') AND category_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_scope_shape", "(role = 'Admin' AND admin_scope = 'Organization' AND branch_id IS NULL AND category_id IS NULL)\nOR (role = 'Admin' AND admin_scope = 'Branch' AND branch_id IS NOT NULL AND category_id IS NULL)\nOR (role IN ('Lead','Mentor') AND branch_id IS NOT NULL AND category_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserBranchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NewBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_branch_id");

                    b.Property<Guid?>("NewCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_category_id");

                    b.Property<Guid?>("OldBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_branch_id");

                    b.Property<Guid?>("OldCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_category_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_branch_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_branch_history_user_id");

                    b.HasIndex("NewBranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_branch_history_new_branch_id_organization_id");

                    b.HasIndex("OldBranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_branch_history_old_branch_id_organization_id");

                    b.HasIndex("OrganizationId", "UserId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_branch_history_organization_user_changed_at");

                    b.ToTable("user_branch_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_branch_history_change", "old_branch_id IS DISTINCT FROM new_branch_id");

                            t.HasCheckConstraint("ck_user_branch_history_reason", "char_length(reason) BETWEEN 5 AND 500");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserCategoryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NewCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_category_id");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("new_role");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("PreviousCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_category_id");

                    b.Property<string>("PreviousRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_role");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_category_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_category_history_user_id");

                    b.HasIndex("BranchId", "OrganizationId")
                        .HasDatabaseName("ix_user_category_history_branch_id_organization_id");

                    b.HasIndex("OrganizationId", "UserId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_user_category_history_organization_user_changed_at");

                    b.ToTable("user_category_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_category_history_reason", "char_length(reason) BETWEEN 5 AND 500");
                        });
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.Category", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Categories.CategorySettings", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithOne()
                        .HasForeignKey("MentorTaskFlow.Domain.Categories.CategorySettings", "CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("MentorTaskFlow.Domain.Categories.Category", "Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_settings_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Tenancy.Branch", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_organization");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.User", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organization");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_branch_scope");

                    b.HasOne("MentorTaskFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "OrganizationId", "BranchId")
                        .HasPrincipalKey("Id", "OrganizationId", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_category_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserBranchHistory", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_branch_history_user");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("NewBranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_branch_history_new_branch_scope");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("OldBranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_branch_history_old_branch_scope");
                });

            modelBuilder.Entity("MentorTaskFlow.Domain.Users.UserCategoryHistory", b =>
                {
                    b.HasOne("MentorTaskFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_history_user");

                    b.HasOne("MentorTaskFlow.Domain.Tenancy.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_category_history_scope");
                });
#pragma warning restore 612, 618
        }
    }
}
